timeout: 7
wallpaper: boot():/boot/wallpaper.jpg
wallpaper_style: stretched
keyboard_layout: qwerty
remember_last_entry: yes
interface_branding: dualys

/Amentys OS
    protocol: limine
    kernel_path: boot():/boot/re
    module_path: boot():/boot/maat
    module_string: maat
    resolution: 1366x768x32
